name: agrah
description: gbbfdzbntn
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.5
  
  
  
  
  
   
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  hooks_riverpod: ^2.4.10
  flutter_riverpod: ^2.4.10
  
  
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  
  
  
  go_router: ^9.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  
  
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3
  

flutter:
  uses-material-design: true

  assets:
    
    - assets/icons/
    
    
    - assets/images/
    
    
    
    
    
    
