name: {{appTitle}}
description: {{description}}
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.5
  {{#hive}}
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  {{/hive}}
  {{#firebase}}
  firebase_core: ^2.14.0
  {{/firebase}}
  {{#firestore}}
  cloud_firestore: ^4.8.2
  {{/firestore}}
  {{#firebase storage}}
  firebase_storage: ^11.2.4
  {{/firebase storage}}
  {{#authentication}}
  firebase_auth: ^4.6.3
  {{/authentication}}
  {{#riverpod}} 
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  hooks_riverpod: ^2.4.10
  flutter_riverpod: ^2.4.10
  {{/riverpod}}
  {{#freezed}}
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  {{/freezed}}
  {{#location}}
  geocoding: ^2.2.0
  geolocator: ^11.0.0
  {{/location}}
  {{#go router}}
  go_router: ^9.0.0
  {{/go router}}
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  
  {{#riverpod}}
  riverpod_lint: ^1.3.2
  riverpod_generator: ^2.2.3
  {{/riverpod}}

flutter:
  uses-material-design: true

  assets:
    {{#icons}}
    - assets/icons/
    {{/icons}}
    {{#images}}
    - assets/images/
    {{/images}}
    {{#videos}}
    - assets/videos/
    {{/videos}}
    {{#gif}}
    - assets/gif/
    {{/gif}}
    
    
    
